version: '3.9'
services:
  uptime-kuma:
    image: louislam/uptime-kuma@sha256:e10376878b88fdeaa554b581695b99b5552fbbbb5344806046a859dcd3a2daf0
    container_name: uptime-kuma_uptime-kuma
    restart: "no"
    volumes:
      - $DOCKER_DATA:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
    labels:
      - traefik.http.routers.uptime-kuma.rule=Host(`uptime.jafner.tools`)
      - traefik.http.routers.uptime-kuma.tls.certresolver=lets-encrypt
networks:
  web: 
    external: true
